<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace GPBMetadata;

class Dy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
äX
dy.protodouyin"ä
Response%
messagesList (2.douyin.Message
cursor (	
fetchInterval (
now (
internalExt (	
	fetchType (6
routeParams (2!.douyin.Response.RouteParamsEntry
heartbeatDuration (
needAck	 (

pushServer
 (	

liveCursor (	
historyNoMore (2
RouteParamsEntry
key (	
value (	:8"š
Message
method (	
payload (
msgId (
msgType (
offset (
needWrdsStore (
wrdsVersion (

wrdsSubKey (	"Ê
ChatMessage
common (2.douyin.Common
user (2.douyin.User
content (	
visibleToSender (&
backgroundImage (2.douyin.Image
fullScreenTextColor (	(
backgroundImageV2 (2.douyin.Image2
publicAreaCommon (2.douyin.PublicAreaCommon 
	giftImage	 (2.douyin.Image

agreeMsgId (
priorityLevel (8
landscapeAreaCommon (2.douyin.LandscapeAreaCommon
	eventTime (

sendReview (
fromIntercom (
intercomHideUserCard (
chatBy (	
individualChatPriority ( 

rtfContent (2.douyin.Text"¡
LandscapeAreaCommon
showHead (
showNickname (
showFontColor (
colorValueList (	3
commentTypeTagsList (2.douyin.CommentTypeTag"‡
RoomUserSeqMessage
common (2.douyin.Common8
	ranksList (2%.douyin.RoomUserSeqMessageContributor
total (
popStr (	8
	seatsList (2%.douyin.RoomUserSeqMessageContributor

popularity (
	totalUser (
totalUserStr (	
totalStr	 (	
onlineUserForAnchor
 (	
totalPvForAnchor (	
upRightStatsStr (	
upRightStatsStrComplete (	"^
CommonTextMessage
common (2.douyin.Common
user (2.douyin.User
scene (	"‰
UpdateFanTicketMessage
common (2.douyin.Common
roomFanTicketCountText (	
roomFanTicketCount (
forceUpdate ("©
RoomUserSeqMessageContributor
score (
user (2.douyin.User
rank (
delta (
isHidden (
scoreDescription (	
exactlyScore (	"±
GiftMessage
common (2.douyin.Common
giftId (
fanTicketCount (

groupCount (
repeatCount (

comboCount (
user (2.douyin.User
toUser (2.douyin.User
	repeatEnd	 (&

textEffect
 (2.douyin.TextEffect
groupId (
incomeTaskgifts (
roomFanTicketCount ((
priority (2.douyin.GiftIMPriority 
gift (2.douyin.GiftStruct
logId (	
sendType (2
publicAreaCommon (2.douyin.PublicAreaCommon%
trayDisplayText (2.douyin.Text
bannedDisplayEffects (
displayForSelf (
interactGiftInfo (	
diyItemInfo (	
minAssetSetList (

totalCount (
clientGiftSource (
toUserIdsList  (
sendTime! (
forceDisplayEffects" (
traceId# (	
effectDisplayTs$ ("£

GiftStruct
image (2.douyin.Image
describe (	
notify (
duration (

id (

forLinkmic (
doodle (
forFansclub	 (
combo
 (
type (
diamondCount (
isDisplayedOnPanel (
primaryEffectId ($
giftLabelIcon (2.douyin.Image
name (	
region (	
manual (	
	forCustom (
icon (2.douyin.Image

actionType ("U
GiftIMPriority
queueSizesList (
selfQueuePriority (
priority ("e

TextEffect*
portrait (2.douyin.TextEffectDetail+
	landscape (2.douyin.TextEffectDetail"¶
TextEffectDetail
text (2.douyin.Text
textFontSize (!

background (2.douyin.Image
start (
duration (	
x (	
y (
width (
height	 (
shadowDx
 (
shadowDy (
shadowRadius (
shadowColor (	
strokeColor (	
strokeWidth ("ï
MemberMessage
common (2.douyin.Common
user (2.douyin.User
memberCount (
operator (2.douyin.User
isSetToAdmin (
	isTopUser (
	rankScore (
	topUserNo (
	enterType	 (
action
 (
actionDescription (	
userId (*
effectConfig (2.douyin.EffectConfig
popStr (	/
enterEffectConfig (2.douyin.EffectConfig&
backgroundImage (2.douyin.Image(
backgroundImageV2 (2.douyin.Image\'
anchorDisplayText (2.douyin.Text2
publicAreaCommon (2.douyin.PublicAreaCommon
userEnterTipType (
anchorEnterTipType ("n
PublicAreaCommon 
	userLabel (2.douyin.Image
userConsumeInRoom (
userSendGiftCntInRoom ("–
EffectConfig
type (
icon (2.douyin.Image
	avatarPos (
text (2.douyin.Text
textIcon (2.douyin.Image
stayTime (
animAssetId (
badge (2.douyin.Image
flexSettingArrayList	 (&
textIconOverlay
 (2.douyin.Image$
animatedBadge (2.douyin.Image
hasSweepLight ( 
textFlexSettingArrayList (
centerAnimAssetId (#
dynamicImage (2.douyin.Image4
extraMap (2".douyin.EffectConfig.ExtraMapEntry
mp4AnimAssetId (
priority (
maxWaitTime (
dressId (	
	alignment (
alignmentOffset (/
ExtraMapEntry
key (	
value (	:8"|
Text
key (	
defaultPatter (	)
defaultFormat (2.douyin.TextFormat%

piecesList (2.douyin.TextPiece"´
	TextPiece
type ("
format (2.douyin.TextFormat
stringValue (	(
	userValue (2.douyin.TextPieceUser(
	giftValue (2.douyin.TextPieceGift*

heartValue (2.douyin.TextPieceHeart4
patternRefValue (2.douyin.TextPiecePatternRef*

imageValue (2.douyin.TextPieceImage"C
TextPieceImage
image (2.douyin.Image
scalingRate (":
TextPiecePatternRef
key (	
defaultPattern (	"
TextPieceHeart
color (	"D
TextPieceGift
giftId (#
nameRef (2.douyin.PatternRef"1

PatternRef
key (	
defaultPattern (	">
TextPieceUser
user (2.douyin.User
	withColon ("£

TextFormat
color (	
bold (
italic (
weight (
italicAngle (
fontSize (
useHeighLightColor (
useRemoteClor ("Ê
LikeMessage
common (2.douyin.Common
count (
total (
color (
user (2.douyin.User
icon (	2
doubleLikeDetail (2.douyin.DoubleLikeDetail6
displayControlInfo (2.douyin.DisplayControlInfo
linkmicGuestUid	 (
scene
 (	0
picoDisplayInfo (2.douyin.PicoDisplayInfo"Ì
SocialMessage
common (2.douyin.Common
user (2.douyin.User
	shareType (
action (
shareTarget (	
followCount (2
publicAreaCommon (2.douyin.PublicAreaCommon"l
PicoDisplayInfo
comboSumCount (
emoji (	 
	emojiIcon (2.douyin.Image
	emojiText (	"_
DoubleLikeDetail

doubleFlag (
seqId (
renewalsNum (
triggersNum ("9
DisplayControlInfo
showText (
	showIcons ("È
EpisodeChatMessage
common (2.douyin.Message
user (2.douyin.User
content (	
visibleToSende ( 
	giftImage (2.douyin.Image

agreeMsgId (
colorValueList	 (	"ˆ
MatchAgainstScoreMessage
common (2.douyin.Common 
against (2.douyin.Against
matchStatus (
displayStatus ("’
Against
leftName (	
leftLogo (2.douyin.Image
leftGoal (	
	rightName (	 
	rightLogo (2.douyin.Image
	rightGoal (	
	timestamp (
version (

leftTeamId (
rightTeamId (
diffSei2absSecond (
finalGoalStage (
currentGoalStage (
leftScoreAddition (
rightScoreAddition (
leftGoalInt (
rightGoalInt ("Ñ
Common
method (	
msgId (
roomId (

createTime (
monitor (
	isShowMsg (
describe (	
foldType	 (
anchorFoldType
 (
priorityScore (
logId (	
msgProcessFilterK (	
msgProcessFilterV (	
user (2.douyin.User
anchorFoldTypeV2 (
processAtSeiTimeMs (
randomDispatchMs (

isDispatch (
	channelId (
diffSei2absSecond (
anchorFoldDuration ("×
User

id (
shortId (
nickName (	
gender (
	Signature (	
Level (
Birthday (
	Telephone (	"
AvatarThumb	 (2.douyin.Image#
AvatarMedium
 (2.douyin.Image"
AvatarLarge (2.douyin.Image
Verified (

Experience (
city (	
Status (

CreateTime (

ModifyTime (
Secret (
ShareQrcodeUri (	
IncomeSharePercent (%
BadgeImageList (2.douyin.Image&

FollowInfo (2.douyin.FollowInfo
	SpecialId (	#
AvatarBorder (2.douyin.Image
Medal (2.douyin.Image(
RealTimeIconsList (2.douyin.Image
	displayId& (	
secUid. (	
fanTicketCountþ (
idStr„ (	
ageRange• ("®

FollowInfo
followingCount (
followerCount (
followStatus (

pushStatus (

remarkName (	
followerCountStr (	
followingCountStr (	"¢
Image
urlListList (	
uri (	
height (
width (
avgColor (	
	imageType (

openWebUrl (	%
content (2.douyin.ImageContent

isAnimated	 (1
FlexSettingList
 (2.douyin.NinePatchSetting1
TextSettingList (2.douyin.NinePatchSetting"+
NinePatchSetting
settingListList (	"W
ImageContent
name (	
	fontColor (	
level (
alternativeText (	"³
	PushFrame
seqId (
logId (
service (
method ((
headersList (2.douyin.HeadersList
payloadEncoding (	
payloadType (	
payload ("
kk	
k ("Í
SendMessageBody
conversationId (	
conversationType (
conversationShortId (
content (	
ext (2.douyin.ExtList
messageType (
ticket (	
clientMessageId (	"%
ExtList
key (	
value (	"·
Rsp	
a (	
b (	
c (	
d (		
e (
f (2.douyin.Rsp.F	
g (		
h
 (	
i (	
j (3
F

q1 (

q3 (

q4 (	

q5 ("²

PreMessage
cmd (

sequenceId (

sdkVersion (	
token (	
refer (
	inboxType (
buildNumber (	0
sendMessageBody (2.douyin.SendMessageBody

aa	 (	
devicePlatform (	$
headers (2.douyin.HeadersList
authType (
biz (	
access (	")
HeadersList
key (	
value (	"[
LiveShoppingMessage
common (2.douyin.Common
msgType (
promotionId ("í
RoomStatsMessage
common (2.douyin.Common
displayShort (	
displayMiddle (	
displayLong (	
displayValue (
displayVersion (
incremental (
isHidden (
total	 (
displayType
 ("c
ProductInfo
promotionId (
index (
targetFlashUidsList (
explainType ("e
CategoryInfo

id (
name (	
promotionIdsList (
type (	
uniqueIndex (	"Ý
ProductChangeMessage
common (2.douyin.Common
updateTimestamp (
updateToast (	2
updateProductInfoList (2.douyin.ProductInfo
total (4
updateCategoryInfoList (2.douyin.CategoryInfo*C
CommentTypeTag
COMMENTTYPETAGUNKNOWN 
COMMENTTYPETAGSTARbproto3'
        , true);

        static::$is_initialized = true;
    }
}

