<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.CategoryInfo</code>
 */
class CategoryInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated int64 promotionIdsList = 3;</code>
     */
    private $promotionIdsList;
    /**
     * Generated from protobuf field <code>string type = 4;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string uniqueIndex = 5;</code>
     */
    protected $uniqueIndex = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $name
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $promotionIdsList
     *     @type string $type
     *     @type string $uniqueIndex
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 promotionIdsList = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPromotionIdsList()
    {
        return $this->promotionIdsList;
    }

    /**
     * Generated from protobuf field <code>repeated int64 promotionIdsList = 3;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPromotionIdsList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->promotionIdsList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uniqueIndex = 5;</code>
     * @return string
     */
    public function getUniqueIndex()
    {
        return $this->uniqueIndex;
    }

    /**
     * Generated from protobuf field <code>string uniqueIndex = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueIndex($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqueIndex = $var;

        return $this;
    }

}

