<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 聊天
 *
 * Generated from protobuf message <code>douyin.ChatMessage</code>
 */
class ChatMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>bool visibleToSender = 4;</code>
     */
    protected $visibleToSender = false;
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 5;</code>
     */
    protected $backgroundImage = null;
    /**
     * Generated from protobuf field <code>string fullScreenTextColor = 6;</code>
     */
    protected $fullScreenTextColor = '';
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 7;</code>
     */
    protected $backgroundImageV2 = null;
    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 8;</code>
     */
    protected $publicAreaCommon = null;
    /**
     * Generated from protobuf field <code>.douyin.Image giftImage = 9;</code>
     */
    protected $giftImage = null;
    /**
     * Generated from protobuf field <code>uint64 agreeMsgId = 11;</code>
     */
    protected $agreeMsgId = 0;
    /**
     * Generated from protobuf field <code>uint32 priorityLevel = 12;</code>
     */
    protected $priorityLevel = 0;
    /**
     * Generated from protobuf field <code>.douyin.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
     */
    protected $landscapeAreaCommon = null;
    /**
     * Generated from protobuf field <code>uint64 eventTime = 15;</code>
     */
    protected $eventTime = 0;
    /**
     * Generated from protobuf field <code>bool sendReview = 16;</code>
     */
    protected $sendReview = false;
    /**
     * Generated from protobuf field <code>bool fromIntercom = 17;</code>
     */
    protected $fromIntercom = false;
    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 18;</code>
     */
    protected $intercomHideUserCard = false;
    /**
     *  repeated chatTagsList = 19;
     *
     * Generated from protobuf field <code>string chatBy = 20;</code>
     */
    protected $chatBy = '';
    /**
     * Generated from protobuf field <code>uint32 individualChatPriority = 21;</code>
     */
    protected $individualChatPriority = 0;
    /**
     * Generated from protobuf field <code>.douyin.Text rtfContent = 22;</code>
     */
    protected $rtfContent = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type \Douyin\User $user
     *     @type string $content
     *     @type bool $visibleToSender
     *     @type \Douyin\Image $backgroundImage
     *     @type string $fullScreenTextColor
     *     @type \Douyin\Image $backgroundImageV2
     *     @type \Douyin\PublicAreaCommon $publicAreaCommon
     *     @type \Douyin\Image $giftImage
     *     @type int|string $agreeMsgId
     *     @type int $priorityLevel
     *     @type \Douyin\LandscapeAreaCommon $landscapeAreaCommon
     *     @type int|string $eventTime
     *     @type bool $sendReview
     *     @type bool $fromIntercom
     *     @type bool $intercomHideUserCard
     *     @type string $chatBy
     *            repeated chatTagsList = 19;
     *     @type int $individualChatPriority
     *     @type \Douyin\Text $rtfContent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @return \Douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool visibleToSender = 4;</code>
     * @return bool
     */
    public function getVisibleToSender()
    {
        return $this->visibleToSender;
    }

    /**
     * Generated from protobuf field <code>bool visibleToSender = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setVisibleToSender($var)
    {
        GPBUtil::checkBool($var);
        $this->visibleToSender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 5;</code>
     * @return \Douyin\Image|null
     */
    public function getBackgroundImage()
    {
        return $this->backgroundImage;
    }

    public function hasBackgroundImage()
    {
        return isset($this->backgroundImage);
    }

    public function clearBackgroundImage()
    {
        unset($this->backgroundImage);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 5;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setBackgroundImage($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->backgroundImage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fullScreenTextColor = 6;</code>
     * @return string
     */
    public function getFullScreenTextColor()
    {
        return $this->fullScreenTextColor;
    }

    /**
     * Generated from protobuf field <code>string fullScreenTextColor = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFullScreenTextColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullScreenTextColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 7;</code>
     * @return \Douyin\Image|null
     */
    public function getBackgroundImageV2()
    {
        return $this->backgroundImageV2;
    }

    public function hasBackgroundImageV2()
    {
        return isset($this->backgroundImageV2);
    }

    public function clearBackgroundImageV2()
    {
        unset($this->backgroundImageV2);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 7;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setBackgroundImageV2($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->backgroundImageV2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 8;</code>
     * @return \Douyin\PublicAreaCommon|null
     */
    public function getPublicAreaCommon()
    {
        return $this->publicAreaCommon;
    }

    public function hasPublicAreaCommon()
    {
        return isset($this->publicAreaCommon);
    }

    public function clearPublicAreaCommon()
    {
        unset($this->publicAreaCommon);
    }

    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 8;</code>
     * @param \Douyin\PublicAreaCommon $var
     * @return $this
     */
    public function setPublicAreaCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\PublicAreaCommon::class);
        $this->publicAreaCommon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image giftImage = 9;</code>
     * @return \Douyin\Image|null
     */
    public function getGiftImage()
    {
        return $this->giftImage;
    }

    public function hasGiftImage()
    {
        return isset($this->giftImage);
    }

    public function clearGiftImage()
    {
        unset($this->giftImage);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image giftImage = 9;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setGiftImage($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->giftImage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 agreeMsgId = 11;</code>
     * @return int|string
     */
    public function getAgreeMsgId()
    {
        return $this->agreeMsgId;
    }

    /**
     * Generated from protobuf field <code>uint64 agreeMsgId = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAgreeMsgId($var)
    {
        GPBUtil::checkUint64($var);
        $this->agreeMsgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 priorityLevel = 12;</code>
     * @return int
     */
    public function getPriorityLevel()
    {
        return $this->priorityLevel;
    }

    /**
     * Generated from protobuf field <code>uint32 priorityLevel = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setPriorityLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->priorityLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
     * @return \Douyin\LandscapeAreaCommon|null
     */
    public function getLandscapeAreaCommon()
    {
        return $this->landscapeAreaCommon;
    }

    public function hasLandscapeAreaCommon()
    {
        return isset($this->landscapeAreaCommon);
    }

    public function clearLandscapeAreaCommon()
    {
        unset($this->landscapeAreaCommon);
    }

    /**
     * Generated from protobuf field <code>.douyin.LandscapeAreaCommon landscapeAreaCommon = 13;</code>
     * @param \Douyin\LandscapeAreaCommon $var
     * @return $this
     */
    public function setLandscapeAreaCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\LandscapeAreaCommon::class);
        $this->landscapeAreaCommon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 eventTime = 15;</code>
     * @return int|string
     */
    public function getEventTime()
    {
        return $this->eventTime;
    }

    /**
     * Generated from protobuf field <code>uint64 eventTime = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->eventTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool sendReview = 16;</code>
     * @return bool
     */
    public function getSendReview()
    {
        return $this->sendReview;
    }

    /**
     * Generated from protobuf field <code>bool sendReview = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendReview($var)
    {
        GPBUtil::checkBool($var);
        $this->sendReview = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool fromIntercom = 17;</code>
     * @return bool
     */
    public function getFromIntercom()
    {
        return $this->fromIntercom;
    }

    /**
     * Generated from protobuf field <code>bool fromIntercom = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setFromIntercom($var)
    {
        GPBUtil::checkBool($var);
        $this->fromIntercom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 18;</code>
     * @return bool
     */
    public function getIntercomHideUserCard()
    {
        return $this->intercomHideUserCard;
    }

    /**
     * Generated from protobuf field <code>bool intercomHideUserCard = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setIntercomHideUserCard($var)
    {
        GPBUtil::checkBool($var);
        $this->intercomHideUserCard = $var;

        return $this;
    }

    /**
     *  repeated chatTagsList = 19;
     *
     * Generated from protobuf field <code>string chatBy = 20;</code>
     * @return string
     */
    public function getChatBy()
    {
        return $this->chatBy;
    }

    /**
     *  repeated chatTagsList = 19;
     *
     * Generated from protobuf field <code>string chatBy = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setChatBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->chatBy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 individualChatPriority = 21;</code>
     * @return int
     */
    public function getIndividualChatPriority()
    {
        return $this->individualChatPriority;
    }

    /**
     * Generated from protobuf field <code>uint32 individualChatPriority = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setIndividualChatPriority($var)
    {
        GPBUtil::checkUint32($var);
        $this->individualChatPriority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Text rtfContent = 22;</code>
     * @return \Douyin\Text|null
     */
    public function getRtfContent()
    {
        return $this->rtfContent;
    }

    public function hasRtfContent()
    {
        return isset($this->rtfContent);
    }

    public function clearRtfContent()
    {
        unset($this->rtfContent);
    }

    /**
     * Generated from protobuf field <code>.douyin.Text rtfContent = 22;</code>
     * @param \Douyin\Text $var
     * @return $this
     */
    public function setRtfContent($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Text::class);
        $this->rtfContent = $var;

        return $this;
    }

}

