<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use UnexpectedValueException;

/**
 * Protobuf type <code>douyin.CommentTypeTag</code>
 */
class CommentTypeTag
{
    /**
     * Generated from protobuf enum <code>COMMENTTYPETAGUNKNOWN = 0;</code>
     */
    const COMMENTTYPETAGUNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>COMMENTTYPETAGSTAR = 1;</code>
     */
    const COMMENTTYPETAGSTAR = 1;

    private static $valueToName = [
        self::COMMENTTYPETAGUNKNOWN => 'COMMENTTYPETAGUNKNOWN',
        self::COMMENTTYPETAGSTAR => 'COMMENTTYPETAGSTAR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

