<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.Common</code>
 */
class Common extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string method = 1;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>uint64 msgId = 2;</code>
     */
    protected $msgId = 0;
    /**
     * Generated from protobuf field <code>uint64 roomId = 3;</code>
     */
    protected $roomId = 0;
    /**
     * Generated from protobuf field <code>uint64 createTime = 4;</code>
     */
    protected $createTime = 0;
    /**
     * Generated from protobuf field <code>uint32 monitor = 5;</code>
     */
    protected $monitor = 0;
    /**
     * Generated from protobuf field <code>bool isShowMsg = 6;</code>
     */
    protected $isShowMsg = false;
    /**
     * Generated from protobuf field <code>string describe = 7;</code>
     */
    protected $describe = '';
    /**
     *  DisplayText displayText = 8;
     *
     * Generated from protobuf field <code>uint64 foldType = 9;</code>
     */
    protected $foldType = 0;
    /**
     * Generated from protobuf field <code>uint64 anchorFoldType = 10;</code>
     */
    protected $anchorFoldType = 0;
    /**
     * Generated from protobuf field <code>uint64 priorityScore = 11;</code>
     */
    protected $priorityScore = 0;
    /**
     * Generated from protobuf field <code>string logId = 12;</code>
     */
    protected $logId = '';
    /**
     * Generated from protobuf field <code>string msgProcessFilterK = 13;</code>
     */
    protected $msgProcessFilterK = '';
    /**
     * Generated from protobuf field <code>string msgProcessFilterV = 14;</code>
     */
    protected $msgProcessFilterV = '';
    /**
     * Generated from protobuf field <code>.douyin.User user = 15;</code>
     */
    protected $user = null;
    /**
     *  Room room = 16;
     *
     * Generated from protobuf field <code>uint64 anchorFoldTypeV2 = 17;</code>
     */
    protected $anchorFoldTypeV2 = 0;
    /**
     * Generated from protobuf field <code>uint64 processAtSeiTimeMs = 18;</code>
     */
    protected $processAtSeiTimeMs = 0;
    /**
     * Generated from protobuf field <code>uint64 randomDispatchMs = 19;</code>
     */
    protected $randomDispatchMs = 0;
    /**
     * Generated from protobuf field <code>bool isDispatch = 20;</code>
     */
    protected $isDispatch = false;
    /**
     * Generated from protobuf field <code>uint64 channelId = 21;</code>
     */
    protected $channelId = 0;
    /**
     * Generated from protobuf field <code>uint64 diffSei2absSecond = 22;</code>
     */
    protected $diffSei2absSecond = 0;
    /**
     * Generated from protobuf field <code>uint64 anchorFoldDuration = 23;</code>
     */
    protected $anchorFoldDuration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $method
     *     @type int|string $msgId
     *     @type int|string $roomId
     *     @type int|string $createTime
     *     @type int $monitor
     *     @type bool $isShowMsg
     *     @type string $describe
     *     @type int|string $foldType
     *            DisplayText displayText = 8;
     *     @type int|string $anchorFoldType
     *     @type int|string $priorityScore
     *     @type string $logId
     *     @type string $msgProcessFilterK
     *     @type string $msgProcessFilterV
     *     @type \Douyin\User $user
     *     @type int|string $anchorFoldTypeV2
     *            Room room = 16;
     *     @type int|string $processAtSeiTimeMs
     *     @type int|string $randomDispatchMs
     *     @type bool $isDispatch
     *     @type int|string $channelId
     *     @type int|string $diffSei2absSecond
     *     @type int|string $anchorFoldDuration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string method = 1;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 msgId = 2;</code>
     * @return int|string
     */
    public function getMsgId()
    {
        return $this->msgId;
    }

    /**
     * Generated from protobuf field <code>uint64 msgId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkUint64($var);
        $this->msgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 roomId = 3;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->roomId;
    }

    /**
     * Generated from protobuf field <code>uint64 roomId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->roomId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 createTime = 4;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     * Generated from protobuf field <code>uint64 createTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->createTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 monitor = 5;</code>
     * @return int
     */
    public function getMonitor()
    {
        return $this->monitor;
    }

    /**
     * Generated from protobuf field <code>uint32 monitor = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMonitor($var)
    {
        GPBUtil::checkUint32($var);
        $this->monitor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isShowMsg = 6;</code>
     * @return bool
     */
    public function getIsShowMsg()
    {
        return $this->isShowMsg;
    }

    /**
     * Generated from protobuf field <code>bool isShowMsg = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsShowMsg($var)
    {
        GPBUtil::checkBool($var);
        $this->isShowMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string describe = 7;</code>
     * @return string
     */
    public function getDescribe()
    {
        return $this->describe;
    }

    /**
     * Generated from protobuf field <code>string describe = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->describe = $var;

        return $this;
    }

    /**
     *  DisplayText displayText = 8;
     *
     * Generated from protobuf field <code>uint64 foldType = 9;</code>
     * @return int|string
     */
    public function getFoldType()
    {
        return $this->foldType;
    }

    /**
     *  DisplayText displayText = 8;
     *
     * Generated from protobuf field <code>uint64 foldType = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFoldType($var)
    {
        GPBUtil::checkUint64($var);
        $this->foldType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorFoldType = 10;</code>
     * @return int|string
     */
    public function getAnchorFoldType()
    {
        return $this->anchorFoldType;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorFoldType = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorFoldType($var)
    {
        GPBUtil::checkUint64($var);
        $this->anchorFoldType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 priorityScore = 11;</code>
     * @return int|string
     */
    public function getPriorityScore()
    {
        return $this->priorityScore;
    }

    /**
     * Generated from protobuf field <code>uint64 priorityScore = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriorityScore($var)
    {
        GPBUtil::checkUint64($var);
        $this->priorityScore = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logId = 12;</code>
     * @return string
     */
    public function getLogId()
    {
        return $this->logId;
    }

    /**
     * Generated from protobuf field <code>string logId = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setLogId($var)
    {
        GPBUtil::checkString($var, True);
        $this->logId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msgProcessFilterK = 13;</code>
     * @return string
     */
    public function getMsgProcessFilterK()
    {
        return $this->msgProcessFilterK;
    }

    /**
     * Generated from protobuf field <code>string msgProcessFilterK = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgProcessFilterK($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgProcessFilterK = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msgProcessFilterV = 14;</code>
     * @return string
     */
    public function getMsgProcessFilterV()
    {
        return $this->msgProcessFilterV;
    }

    /**
     * Generated from protobuf field <code>string msgProcessFilterV = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgProcessFilterV($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgProcessFilterV = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 15;</code>
     * @return \Douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 15;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     *  Room room = 16;
     *
     * Generated from protobuf field <code>uint64 anchorFoldTypeV2 = 17;</code>
     * @return int|string
     */
    public function getAnchorFoldTypeV2()
    {
        return $this->anchorFoldTypeV2;
    }

    /**
     *  Room room = 16;
     *
     * Generated from protobuf field <code>uint64 anchorFoldTypeV2 = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorFoldTypeV2($var)
    {
        GPBUtil::checkUint64($var);
        $this->anchorFoldTypeV2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 processAtSeiTimeMs = 18;</code>
     * @return int|string
     */
    public function getProcessAtSeiTimeMs()
    {
        return $this->processAtSeiTimeMs;
    }

    /**
     * Generated from protobuf field <code>uint64 processAtSeiTimeMs = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessAtSeiTimeMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->processAtSeiTimeMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 randomDispatchMs = 19;</code>
     * @return int|string
     */
    public function getRandomDispatchMs()
    {
        return $this->randomDispatchMs;
    }

    /**
     * Generated from protobuf field <code>uint64 randomDispatchMs = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRandomDispatchMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->randomDispatchMs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isDispatch = 20;</code>
     * @return bool
     */
    public function getIsDispatch()
    {
        return $this->isDispatch;
    }

    /**
     * Generated from protobuf field <code>bool isDispatch = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDispatch($var)
    {
        GPBUtil::checkBool($var);
        $this->isDispatch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 channelId = 21;</code>
     * @return int|string
     */
    public function getChannelId()
    {
        return $this->channelId;
    }

    /**
     * Generated from protobuf field <code>uint64 channelId = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setChannelId($var)
    {
        GPBUtil::checkUint64($var);
        $this->channelId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 diffSei2absSecond = 22;</code>
     * @return int|string
     */
    public function getDiffSei2AbsSecond()
    {
        return $this->diffSei2absSecond;
    }

    /**
     * Generated from protobuf field <code>uint64 diffSei2absSecond = 22;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiffSei2AbsSecond($var)
    {
        GPBUtil::checkUint64($var);
        $this->diffSei2absSecond = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorFoldDuration = 23;</code>
     * @return int|string
     */
    public function getAnchorFoldDuration()
    {
        return $this->anchorFoldDuration;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorFoldDuration = 23;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorFoldDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->anchorFoldDuration = $var;

        return $this;
    }

}

