<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.DisplayControlInfo</code>
 */
class DisplayControlInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool showText = 1;</code>
     */
    protected $showText = false;
    /**
     * Generated from protobuf field <code>bool showIcons = 2;</code>
     */
    protected $showIcons = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $showText
     *     @type bool $showIcons
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool showText = 1;</code>
     * @return bool
     */
    public function getShowText()
    {
        return $this->showText;
    }

    /**
     * Generated from protobuf field <code>bool showText = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowText($var)
    {
        GPBUtil::checkBool($var);
        $this->showText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool showIcons = 2;</code>
     * @return bool
     */
    public function getShowIcons()
    {
        return $this->showIcons;
    }

    /**
     * Generated from protobuf field <code>bool showIcons = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowIcons($var)
    {
        GPBUtil::checkBool($var);
        $this->showIcons = $var;

        return $this;
    }

}

