<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.DoubleLikeDetail</code>
 */
class DoubleLikeDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool doubleFlag = 1;</code>
     */
    protected $doubleFlag = false;
    /**
     * Generated from protobuf field <code>uint32 seqId = 2;</code>
     */
    protected $seqId = 0;
    /**
     * Generated from protobuf field <code>uint32 renewalsNum = 3;</code>
     */
    protected $renewalsNum = 0;
    /**
     * Generated from protobuf field <code>uint32 triggersNum = 4;</code>
     */
    protected $triggersNum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $doubleFlag
     *     @type int $seqId
     *     @type int $renewalsNum
     *     @type int $triggersNum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool doubleFlag = 1;</code>
     * @return bool
     */
    public function getDoubleFlag()
    {
        return $this->doubleFlag;
    }

    /**
     * Generated from protobuf field <code>bool doubleFlag = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDoubleFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->doubleFlag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 seqId = 2;</code>
     * @return int
     */
    public function getSeqId()
    {
        return $this->seqId;
    }

    /**
     * Generated from protobuf field <code>uint32 seqId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSeqId($var)
    {
        GPBUtil::checkUint32($var);
        $this->seqId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 renewalsNum = 3;</code>
     * @return int
     */
    public function getRenewalsNum()
    {
        return $this->renewalsNum;
    }

    /**
     * Generated from protobuf field <code>uint32 renewalsNum = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRenewalsNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->renewalsNum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 triggersNum = 4;</code>
     * @return int
     */
    public function getTriggersNum()
    {
        return $this->triggersNum;
    }

    /**
     * Generated from protobuf field <code>uint32 triggersNum = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTriggersNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->triggersNum = $var;

        return $this;
    }

}

