<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.GiftStruct</code>
 */
class GiftStruct extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Image image = 1;</code>
     */
    protected $image = null;
    /**
     * Generated from protobuf field <code>string describe = 2;</code>
     */
    protected $describe = '';
    /**
     * Generated from protobuf field <code>bool notify = 3;</code>
     */
    protected $notify = false;
    /**
     * Generated from protobuf field <code>uint64 duration = 4;</code>
     */
    protected $duration = 0;
    /**
     * Generated from protobuf field <code>uint64 id = 5;</code>
     */
    protected $id = 0;
    /**
     *  GiftStructFansClubInfo fansclubInfo = 6;
     *
     * Generated from protobuf field <code>bool forLinkmic = 7;</code>
     */
    protected $forLinkmic = false;
    /**
     * Generated from protobuf field <code>bool doodle = 8;</code>
     */
    protected $doodle = false;
    /**
     * Generated from protobuf field <code>bool forFansclub = 9;</code>
     */
    protected $forFansclub = false;
    /**
     * Generated from protobuf field <code>bool combo = 10;</code>
     */
    protected $combo = false;
    /**
     * Generated from protobuf field <code>uint32 type = 11;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint32 diamondCount = 12;</code>
     */
    protected $diamondCount = 0;
    /**
     * Generated from protobuf field <code>bool isDisplayedOnPanel = 13;</code>
     */
    protected $isDisplayedOnPanel = false;
    /**
     * Generated from protobuf field <code>uint64 primaryEffectId = 14;</code>
     */
    protected $primaryEffectId = 0;
    /**
     * Generated from protobuf field <code>.douyin.Image giftLabelIcon = 15;</code>
     */
    protected $giftLabelIcon = null;
    /**
     * Generated from protobuf field <code>string name = 16;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string region = 17;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string manual = 18;</code>
     */
    protected $manual = '';
    /**
     * Generated from protobuf field <code>bool forCustom = 19;</code>
     */
    protected $forCustom = false;
    /**
     *  specialEffectsMap = 20;
     *
     * Generated from protobuf field <code>.douyin.Image icon = 21;</code>
     */
    protected $icon = null;
    /**
     * fixme 后面的就不写了还有几十个属性
     *
     * Generated from protobuf field <code>uint32 actionType = 22;</code>
     */
    protected $actionType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Image $image
     *     @type string $describe
     *     @type bool $notify
     *     @type int|string $duration
     *     @type int|string $id
     *     @type bool $forLinkmic
     *            GiftStructFansClubInfo fansclubInfo = 6;
     *     @type bool $doodle
     *     @type bool $forFansclub
     *     @type bool $combo
     *     @type int $type
     *     @type int $diamondCount
     *     @type bool $isDisplayedOnPanel
     *     @type int|string $primaryEffectId
     *     @type \Douyin\Image $giftLabelIcon
     *     @type string $name
     *     @type string $region
     *     @type string $manual
     *     @type bool $forCustom
     *     @type \Douyin\Image $icon
     *            specialEffectsMap = 20;
     *     @type int $actionType
     *           fixme 后面的就不写了还有几十个属性
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image image = 1;</code>
     * @return \Douyin\Image|null
     */
    public function getImage()
    {
        return $this->image;
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image image = 1;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string describe = 2;</code>
     * @return string
     */
    public function getDescribe()
    {
        return $this->describe;
    }

    /**
     * Generated from protobuf field <code>string describe = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescribe($var)
    {
        GPBUtil::checkString($var, True);
        $this->describe = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool notify = 3;</code>
     * @return bool
     */
    public function getNotify()
    {
        return $this->notify;
    }

    /**
     * Generated from protobuf field <code>bool notify = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotify($var)
    {
        GPBUtil::checkBool($var);
        $this->notify = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 duration = 4;</code>
     * @return int|string
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint64 duration = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint64($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 5;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *  GiftStructFansClubInfo fansclubInfo = 6;
     *
     * Generated from protobuf field <code>bool forLinkmic = 7;</code>
     * @return bool
     */
    public function getForLinkmic()
    {
        return $this->forLinkmic;
    }

    /**
     *  GiftStructFansClubInfo fansclubInfo = 6;
     *
     * Generated from protobuf field <code>bool forLinkmic = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setForLinkmic($var)
    {
        GPBUtil::checkBool($var);
        $this->forLinkmic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool doodle = 8;</code>
     * @return bool
     */
    public function getDoodle()
    {
        return $this->doodle;
    }

    /**
     * Generated from protobuf field <code>bool doodle = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setDoodle($var)
    {
        GPBUtil::checkBool($var);
        $this->doodle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool forFansclub = 9;</code>
     * @return bool
     */
    public function getForFansclub()
    {
        return $this->forFansclub;
    }

    /**
     * Generated from protobuf field <code>bool forFansclub = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setForFansclub($var)
    {
        GPBUtil::checkBool($var);
        $this->forFansclub = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool combo = 10;</code>
     * @return bool
     */
    public function getCombo()
    {
        return $this->combo;
    }

    /**
     * Generated from protobuf field <code>bool combo = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setCombo($var)
    {
        GPBUtil::checkBool($var);
        $this->combo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 11;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 diamondCount = 12;</code>
     * @return int
     */
    public function getDiamondCount()
    {
        return $this->diamondCount;
    }

    /**
     * Generated from protobuf field <code>uint32 diamondCount = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDiamondCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->diamondCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isDisplayedOnPanel = 13;</code>
     * @return bool
     */
    public function getIsDisplayedOnPanel()
    {
        return $this->isDisplayedOnPanel;
    }

    /**
     * Generated from protobuf field <code>bool isDisplayedOnPanel = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDisplayedOnPanel($var)
    {
        GPBUtil::checkBool($var);
        $this->isDisplayedOnPanel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 primaryEffectId = 14;</code>
     * @return int|string
     */
    public function getPrimaryEffectId()
    {
        return $this->primaryEffectId;
    }

    /**
     * Generated from protobuf field <code>uint64 primaryEffectId = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrimaryEffectId($var)
    {
        GPBUtil::checkUint64($var);
        $this->primaryEffectId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image giftLabelIcon = 15;</code>
     * @return \Douyin\Image|null
     */
    public function getGiftLabelIcon()
    {
        return $this->giftLabelIcon;
    }

    public function hasGiftLabelIcon()
    {
        return isset($this->giftLabelIcon);
    }

    public function clearGiftLabelIcon()
    {
        unset($this->giftLabelIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image giftLabelIcon = 15;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setGiftLabelIcon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->giftLabelIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 16;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 17;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string manual = 18;</code>
     * @return string
     */
    public function getManual()
    {
        return $this->manual;
    }

    /**
     * Generated from protobuf field <code>string manual = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setManual($var)
    {
        GPBUtil::checkString($var, True);
        $this->manual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool forCustom = 19;</code>
     * @return bool
     */
    public function getForCustom()
    {
        return $this->forCustom;
    }

    /**
     * Generated from protobuf field <code>bool forCustom = 19;</code>
     * @param bool $var
     * @return $this
     */
    public function setForCustom($var)
    {
        GPBUtil::checkBool($var);
        $this->forCustom = $var;

        return $this;
    }

    /**
     *  specialEffectsMap = 20;
     *
     * Generated from protobuf field <code>.douyin.Image icon = 21;</code>
     * @return \Douyin\Image|null
     */
    public function getIcon()
    {
        return $this->icon;
    }

    public function hasIcon()
    {
        return isset($this->icon);
    }

    public function clearIcon()
    {
        unset($this->icon);
    }

    /**
     *  specialEffectsMap = 20;
     *
     * Generated from protobuf field <code>.douyin.Image icon = 21;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->icon = $var;

        return $this;
    }

    /**
     * fixme 后面的就不写了还有几十个属性
     *
     * Generated from protobuf field <code>uint32 actionType = 22;</code>
     * @return int
     */
    public function getActionType()
    {
        return $this->actionType;
    }

    /**
     * fixme 后面的就不写了还有几十个属性
     *
     * Generated from protobuf field <code>uint32 actionType = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setActionType($var)
    {
        GPBUtil::checkUint32($var);
        $this->actionType = $var;

        return $this;
    }

}

