<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.ImageContent</code>
 */
class ImageContent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string fontColor = 2;</code>
     */
    protected $fontColor = '';
    /**
     * Generated from protobuf field <code>uint64 level = 3;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string alternativeText = 4;</code>
     */
    protected $alternativeText = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $fontColor
     *     @type int|string $level
     *     @type string $alternativeText
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fontColor = 2;</code>
     * @return string
     */
    public function getFontColor()
    {
        return $this->fontColor;
    }

    /**
     * Generated from protobuf field <code>string fontColor = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFontColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->fontColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 level = 3;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>uint64 level = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkUint64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alternativeText = 4;</code>
     * @return string
     */
    public function getAlternativeText()
    {
        return $this->alternativeText;
    }

    /**
     * Generated from protobuf field <code>string alternativeText = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAlternativeText($var)
    {
        GPBUtil::checkString($var, True);
        $this->alternativeText = $var;

        return $this;
    }

}

