<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.LandscapeAreaCommon</code>
 */
class LandscapeAreaCommon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool showHead = 1;</code>
     */
    protected $showHead = false;
    /**
     * Generated from protobuf field <code>bool showNickname = 2;</code>
     */
    protected $showNickname = false;
    /**
     * Generated from protobuf field <code>bool showFontColor = 3;</code>
     */
    protected $showFontColor = false;
    /**
     * Generated from protobuf field <code>repeated string colorValueList = 4;</code>
     */
    private $colorValueList;
    /**
     * Generated from protobuf field <code>repeated .douyin.CommentTypeTag commentTypeTagsList = 5;</code>
     */
    private $commentTypeTagsList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $showHead
     *     @type bool $showNickname
     *     @type bool $showFontColor
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $colorValueList
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $commentTypeTagsList
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool showHead = 1;</code>
     * @return bool
     */
    public function getShowHead()
    {
        return $this->showHead;
    }

    /**
     * Generated from protobuf field <code>bool showHead = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowHead($var)
    {
        GPBUtil::checkBool($var);
        $this->showHead = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool showNickname = 2;</code>
     * @return bool
     */
    public function getShowNickname()
    {
        return $this->showNickname;
    }

    /**
     * Generated from protobuf field <code>bool showNickname = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowNickname($var)
    {
        GPBUtil::checkBool($var);
        $this->showNickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool showFontColor = 3;</code>
     * @return bool
     */
    public function getShowFontColor()
    {
        return $this->showFontColor;
    }

    /**
     * Generated from protobuf field <code>bool showFontColor = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowFontColor($var)
    {
        GPBUtil::checkBool($var);
        $this->showFontColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string colorValueList = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColorValueList()
    {
        return $this->colorValueList;
    }

    /**
     * Generated from protobuf field <code>repeated string colorValueList = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColorValueList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->colorValueList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.CommentTypeTag commentTypeTagsList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCommentTypeTagsList()
    {
        return $this->commentTypeTagsList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.CommentTypeTag commentTypeTagsList = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCommentTypeTagsList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Douyin\CommentTypeTag::class);
        $this->commentTypeTagsList = $arr;

        return $this;
    }

}

