<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 点赞
 *
 * Generated from protobuf message <code>douyin.LikeMessage</code>
 */
class LikeMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     */
    protected $count = 0;
    /**
     * Generated from protobuf field <code>uint64 total = 3;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>uint64 color = 4;</code>
     */
    protected $color = 0;
    /**
     * Generated from protobuf field <code>.douyin.User user = 5;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>string icon = 6;</code>
     */
    protected $icon = '';
    /**
     * Generated from protobuf field <code>.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
     */
    protected $doubleLikeDetail = null;
    /**
     * Generated from protobuf field <code>.douyin.DisplayControlInfo displayControlInfo = 8;</code>
     */
    protected $displayControlInfo = null;
    /**
     * Generated from protobuf field <code>uint64 linkmicGuestUid = 9;</code>
     */
    protected $linkmicGuestUid = 0;
    /**
     * Generated from protobuf field <code>string scene = 10;</code>
     */
    protected $scene = '';
    /**
     * Generated from protobuf field <code>.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
     */
    protected $picoDisplayInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type int|string $count
     *     @type int|string $total
     *     @type int|string $color
     *     @type \Douyin\User $user
     *     @type string $icon
     *     @type \Douyin\DoubleLikeDetail $doubleLikeDetail
     *     @type \Douyin\DisplayControlInfo $displayControlInfo
     *     @type int|string $linkmicGuestUid
     *     @type string $scene
     *     @type \Douyin\PicoDisplayInfo $picoDisplayInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>uint64 count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total = 3;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint64 total = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 color = 4;</code>
     * @return int|string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>uint64 color = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkUint64($var);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 5;</code>
     * @return \Douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 5;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 6;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
     * @return \Douyin\DoubleLikeDetail|null
     */
    public function getDoubleLikeDetail()
    {
        return $this->doubleLikeDetail;
    }

    public function hasDoubleLikeDetail()
    {
        return isset($this->doubleLikeDetail);
    }

    public function clearDoubleLikeDetail()
    {
        unset($this->doubleLikeDetail);
    }

    /**
     * Generated from protobuf field <code>.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
     * @param \Douyin\DoubleLikeDetail $var
     * @return $this
     */
    public function setDoubleLikeDetail($var)
    {
        GPBUtil::checkMessage($var, \Douyin\DoubleLikeDetail::class);
        $this->doubleLikeDetail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.DisplayControlInfo displayControlInfo = 8;</code>
     * @return \Douyin\DisplayControlInfo|null
     */
    public function getDisplayControlInfo()
    {
        return $this->displayControlInfo;
    }

    public function hasDisplayControlInfo()
    {
        return isset($this->displayControlInfo);
    }

    public function clearDisplayControlInfo()
    {
        unset($this->displayControlInfo);
    }

    /**
     * Generated from protobuf field <code>.douyin.DisplayControlInfo displayControlInfo = 8;</code>
     * @param \Douyin\DisplayControlInfo $var
     * @return $this
     */
    public function setDisplayControlInfo($var)
    {
        GPBUtil::checkMessage($var, \Douyin\DisplayControlInfo::class);
        $this->displayControlInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 linkmicGuestUid = 9;</code>
     * @return int|string
     */
    public function getLinkmicGuestUid()
    {
        return $this->linkmicGuestUid;
    }

    /**
     * Generated from protobuf field <code>uint64 linkmicGuestUid = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLinkmicGuestUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->linkmicGuestUid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scene = 10;</code>
     * @return string
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * Generated from protobuf field <code>string scene = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkString($var, True);
        $this->scene = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
     * @return \Douyin\PicoDisplayInfo|null
     */
    public function getPicoDisplayInfo()
    {
        return $this->picoDisplayInfo;
    }

    public function hasPicoDisplayInfo()
    {
        return isset($this->picoDisplayInfo);
    }

    public function clearPicoDisplayInfo()
    {
        unset($this->picoDisplayInfo);
    }

    /**
     * Generated from protobuf field <code>.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
     * @param \Douyin\PicoDisplayInfo $var
     * @return $this
     */
    public function setPicoDisplayInfo($var)
    {
        GPBUtil::checkMessage($var, \Douyin\PicoDisplayInfo::class);
        $this->picoDisplayInfo = $var;

        return $this;
    }

}

