<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.LiveShoppingMessage</code>
 */
class LiveShoppingMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>int32 msgType = 2;</code>
     */
    protected $msgType = 0;
    /**
     * Generated from protobuf field <code>int64 promotionId = 4;</code>
     */
    protected $promotionId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type int $msgType
     *     @type int|string $promotionId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 msgType = 2;</code>
     * @return int
     */
    public function getMsgType()
    {
        return $this->msgType;
    }

    /**
     * Generated from protobuf field <code>int32 msgType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 promotionId = 4;</code>
     * @return int|string
     */
    public function getPromotionId()
    {
        return $this->promotionId;
    }

    /**
     * Generated from protobuf field <code>int64 promotionId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPromotionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->promotionId = $var;

        return $this;
    }

}

