<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 成员消息
 *
 * Generated from protobuf message <code>douyin.MemberMessage</code>
 */
class MemberMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>uint64 memberCount = 3;</code>
     */
    protected $memberCount = 0;
    /**
     * Generated from protobuf field <code>.douyin.User operator = 4;</code>
     */
    protected $operator = null;
    /**
     * Generated from protobuf field <code>bool isSetToAdmin = 5;</code>
     */
    protected $isSetToAdmin = false;
    /**
     * Generated from protobuf field <code>bool isTopUser = 6;</code>
     */
    protected $isTopUser = false;
    /**
     * Generated from protobuf field <code>uint64 rankScore = 7;</code>
     */
    protected $rankScore = 0;
    /**
     * Generated from protobuf field <code>uint64 topUserNo = 8;</code>
     */
    protected $topUserNo = 0;
    /**
     * Generated from protobuf field <code>uint64 enterType = 9;</code>
     */
    protected $enterType = 0;
    /**
     * Generated from protobuf field <code>uint64 action = 10;</code>
     */
    protected $action = 0;
    /**
     * Generated from protobuf field <code>string actionDescription = 11;</code>
     */
    protected $actionDescription = '';
    /**
     * Generated from protobuf field <code>uint64 userId = 12;</code>
     */
    protected $userId = 0;
    /**
     * Generated from protobuf field <code>.douyin.EffectConfig effectConfig = 13;</code>
     */
    protected $effectConfig = null;
    /**
     * Generated from protobuf field <code>string popStr = 14;</code>
     */
    protected $popStr = '';
    /**
     * Generated from protobuf field <code>.douyin.EffectConfig enterEffectConfig = 15;</code>
     */
    protected $enterEffectConfig = null;
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 16;</code>
     */
    protected $backgroundImage = null;
    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 17;</code>
     */
    protected $backgroundImageV2 = null;
    /**
     * Generated from protobuf field <code>.douyin.Text anchorDisplayText = 18;</code>
     */
    protected $anchorDisplayText = null;
    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
     */
    protected $publicAreaCommon = null;
    /**
     * Generated from protobuf field <code>uint64 userEnterTipType = 20;</code>
     */
    protected $userEnterTipType = 0;
    /**
     * Generated from protobuf field <code>uint64 anchorEnterTipType = 21;</code>
     */
    protected $anchorEnterTipType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type \Douyin\User $user
     *     @type int|string $memberCount
     *     @type \Douyin\User $operator
     *     @type bool $isSetToAdmin
     *     @type bool $isTopUser
     *     @type int|string $rankScore
     *     @type int|string $topUserNo
     *     @type int|string $enterType
     *     @type int|string $action
     *     @type string $actionDescription
     *     @type int|string $userId
     *     @type \Douyin\EffectConfig $effectConfig
     *     @type string $popStr
     *     @type \Douyin\EffectConfig $enterEffectConfig
     *     @type \Douyin\Image $backgroundImage
     *     @type \Douyin\Image $backgroundImageV2
     *     @type \Douyin\Text $anchorDisplayText
     *     @type \Douyin\PublicAreaCommon $publicAreaCommon
     *     @type int|string $userEnterTipType
     *     @type int|string $anchorEnterTipType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @return \Douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 memberCount = 3;</code>
     * @return int|string
     */
    public function getMemberCount()
    {
        return $this->memberCount;
    }

    /**
     * Generated from protobuf field <code>uint64 memberCount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->memberCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User operator = 4;</code>
     * @return \Douyin\User|null
     */
    public function getOperator()
    {
        return $this->operator;
    }

    public function hasOperator()
    {
        return isset($this->operator);
    }

    public function clearOperator()
    {
        unset($this->operator);
    }

    /**
     * Generated from protobuf field <code>.douyin.User operator = 4;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isSetToAdmin = 5;</code>
     * @return bool
     */
    public function getIsSetToAdmin()
    {
        return $this->isSetToAdmin;
    }

    /**
     * Generated from protobuf field <code>bool isSetToAdmin = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSetToAdmin($var)
    {
        GPBUtil::checkBool($var);
        $this->isSetToAdmin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isTopUser = 6;</code>
     * @return bool
     */
    public function getIsTopUser()
    {
        return $this->isTopUser;
    }

    /**
     * Generated from protobuf field <code>bool isTopUser = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTopUser($var)
    {
        GPBUtil::checkBool($var);
        $this->isTopUser = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 rankScore = 7;</code>
     * @return int|string
     */
    public function getRankScore()
    {
        return $this->rankScore;
    }

    /**
     * Generated from protobuf field <code>uint64 rankScore = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRankScore($var)
    {
        GPBUtil::checkUint64($var);
        $this->rankScore = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 topUserNo = 8;</code>
     * @return int|string
     */
    public function getTopUserNo()
    {
        return $this->topUserNo;
    }

    /**
     * Generated from protobuf field <code>uint64 topUserNo = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTopUserNo($var)
    {
        GPBUtil::checkUint64($var);
        $this->topUserNo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 enterType = 9;</code>
     * @return int|string
     */
    public function getEnterType()
    {
        return $this->enterType;
    }

    /**
     * Generated from protobuf field <code>uint64 enterType = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEnterType($var)
    {
        GPBUtil::checkUint64($var);
        $this->enterType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 action = 10;</code>
     * @return int|string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>uint64 action = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkUint64($var);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string actionDescription = 11;</code>
     * @return string
     */
    public function getActionDescription()
    {
        return $this->actionDescription;
    }

    /**
     * Generated from protobuf field <code>string actionDescription = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setActionDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->actionDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 12;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>uint64 userId = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.EffectConfig effectConfig = 13;</code>
     * @return \Douyin\EffectConfig|null
     */
    public function getEffectConfig()
    {
        return $this->effectConfig;
    }

    public function hasEffectConfig()
    {
        return isset($this->effectConfig);
    }

    public function clearEffectConfig()
    {
        unset($this->effectConfig);
    }

    /**
     * Generated from protobuf field <code>.douyin.EffectConfig effectConfig = 13;</code>
     * @param \Douyin\EffectConfig $var
     * @return $this
     */
    public function setEffectConfig($var)
    {
        GPBUtil::checkMessage($var, \Douyin\EffectConfig::class);
        $this->effectConfig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string popStr = 14;</code>
     * @return string
     */
    public function getPopStr()
    {
        return $this->popStr;
    }

    /**
     * Generated from protobuf field <code>string popStr = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setPopStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->popStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.EffectConfig enterEffectConfig = 15;</code>
     * @return \Douyin\EffectConfig|null
     */
    public function getEnterEffectConfig()
    {
        return $this->enterEffectConfig;
    }

    public function hasEnterEffectConfig()
    {
        return isset($this->enterEffectConfig);
    }

    public function clearEnterEffectConfig()
    {
        unset($this->enterEffectConfig);
    }

    /**
     * Generated from protobuf field <code>.douyin.EffectConfig enterEffectConfig = 15;</code>
     * @param \Douyin\EffectConfig $var
     * @return $this
     */
    public function setEnterEffectConfig($var)
    {
        GPBUtil::checkMessage($var, \Douyin\EffectConfig::class);
        $this->enterEffectConfig = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 16;</code>
     * @return \Douyin\Image|null
     */
    public function getBackgroundImage()
    {
        return $this->backgroundImage;
    }

    public function hasBackgroundImage()
    {
        return isset($this->backgroundImage);
    }

    public function clearBackgroundImage()
    {
        unset($this->backgroundImage);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImage = 16;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setBackgroundImage($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->backgroundImage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 17;</code>
     * @return \Douyin\Image|null
     */
    public function getBackgroundImageV2()
    {
        return $this->backgroundImageV2;
    }

    public function hasBackgroundImageV2()
    {
        return isset($this->backgroundImageV2);
    }

    public function clearBackgroundImageV2()
    {
        unset($this->backgroundImageV2);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image backgroundImageV2 = 17;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setBackgroundImageV2($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->backgroundImageV2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Text anchorDisplayText = 18;</code>
     * @return \Douyin\Text|null
     */
    public function getAnchorDisplayText()
    {
        return $this->anchorDisplayText;
    }

    public function hasAnchorDisplayText()
    {
        return isset($this->anchorDisplayText);
    }

    public function clearAnchorDisplayText()
    {
        unset($this->anchorDisplayText);
    }

    /**
     * Generated from protobuf field <code>.douyin.Text anchorDisplayText = 18;</code>
     * @param \Douyin\Text $var
     * @return $this
     */
    public function setAnchorDisplayText($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Text::class);
        $this->anchorDisplayText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
     * @return \Douyin\PublicAreaCommon|null
     */
    public function getPublicAreaCommon()
    {
        return $this->publicAreaCommon;
    }

    public function hasPublicAreaCommon()
    {
        return isset($this->publicAreaCommon);
    }

    public function clearPublicAreaCommon()
    {
        unset($this->publicAreaCommon);
    }

    /**
     * Generated from protobuf field <code>.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
     * @param \Douyin\PublicAreaCommon $var
     * @return $this
     */
    public function setPublicAreaCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\PublicAreaCommon::class);
        $this->publicAreaCommon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userEnterTipType = 20;</code>
     * @return int|string
     */
    public function getUserEnterTipType()
    {
        return $this->userEnterTipType;
    }

    /**
     * Generated from protobuf field <code>uint64 userEnterTipType = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserEnterTipType($var)
    {
        GPBUtil::checkUint64($var);
        $this->userEnterTipType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorEnterTipType = 21;</code>
     * @return int|string
     */
    public function getAnchorEnterTipType()
    {
        return $this->anchorEnterTipType;
    }

    /**
     * Generated from protobuf field <code>uint64 anchorEnterTipType = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorEnterTipType($var)
    {
        GPBUtil::checkUint64($var);
        $this->anchorEnterTipType = $var;

        return $this;
    }

}

