<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.PicoDisplayInfo</code>
 */
class PicoDisplayInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 comboSumCount = 1;</code>
     */
    protected $comboSumCount = 0;
    /**
     * Generated from protobuf field <code>string emoji = 2;</code>
     */
    protected $emoji = '';
    /**
     * Generated from protobuf field <code>.douyin.Image emojiIcon = 3;</code>
     */
    protected $emojiIcon = null;
    /**
     * Generated from protobuf field <code>string emojiText = 4;</code>
     */
    protected $emojiText = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $comboSumCount
     *     @type string $emoji
     *     @type \Douyin\Image $emojiIcon
     *     @type string $emojiText
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 comboSumCount = 1;</code>
     * @return int|string
     */
    public function getComboSumCount()
    {
        return $this->comboSumCount;
    }

    /**
     * Generated from protobuf field <code>uint64 comboSumCount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setComboSumCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->comboSumCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string emoji = 2;</code>
     * @return string
     */
    public function getEmoji()
    {
        return $this->emoji;
    }

    /**
     * Generated from protobuf field <code>string emoji = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmoji($var)
    {
        GPBUtil::checkString($var, True);
        $this->emoji = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image emojiIcon = 3;</code>
     * @return \Douyin\Image|null
     */
    public function getEmojiIcon()
    {
        return $this->emojiIcon;
    }

    public function hasEmojiIcon()
    {
        return isset($this->emojiIcon);
    }

    public function clearEmojiIcon()
    {
        unset($this->emojiIcon);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image emojiIcon = 3;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setEmojiIcon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->emojiIcon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string emojiText = 4;</code>
     * @return string
     */
    public function getEmojiText()
    {
        return $this->emojiText;
    }

    /**
     * Generated from protobuf field <code>string emojiText = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEmojiText($var)
    {
        GPBUtil::checkString($var, True);
        $this->emojiText = $var;

        return $this;
    }

}

