<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.PublicAreaCommon</code>
 */
class PublicAreaCommon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Image userLabel = 1;</code>
     */
    protected $userLabel = null;
    /**
     * Generated from protobuf field <code>uint64 userConsumeInRoom = 2;</code>
     */
    protected $userConsumeInRoom = 0;
    /**
     * Generated from protobuf field <code>uint64 userSendGiftCntInRoom = 3;</code>
     */
    protected $userSendGiftCntInRoom = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Image $userLabel
     *     @type int|string $userConsumeInRoom
     *     @type int|string $userSendGiftCntInRoom
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image userLabel = 1;</code>
     * @return \Douyin\Image|null
     */
    public function getUserLabel()
    {
        return $this->userLabel;
    }

    public function hasUserLabel()
    {
        return isset($this->userLabel);
    }

    public function clearUserLabel()
    {
        unset($this->userLabel);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image userLabel = 1;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setUserLabel($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->userLabel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userConsumeInRoom = 2;</code>
     * @return int|string
     */
    public function getUserConsumeInRoom()
    {
        return $this->userConsumeInRoom;
    }

    /**
     * Generated from protobuf field <code>uint64 userConsumeInRoom = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserConsumeInRoom($var)
    {
        GPBUtil::checkUint64($var);
        $this->userConsumeInRoom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 userSendGiftCntInRoom = 3;</code>
     * @return int|string
     */
    public function getUserSendGiftCntInRoom()
    {
        return $this->userSendGiftCntInRoom;
    }

    /**
     * Generated from protobuf field <code>uint64 userSendGiftCntInRoom = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserSendGiftCntInRoom($var)
    {
        GPBUtil::checkUint64($var);
        $this->userSendGiftCntInRoom = $var;

        return $this;
    }

}

