<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.PushFrame</code>
 */
class PushFrame extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 seqId = 1;</code>
     */
    protected $seqId = 0;
    /**
     * Generated from protobuf field <code>uint64 logId = 2;</code>
     */
    protected $logId = 0;
    /**
     * Generated from protobuf field <code>uint64 service = 3;</code>
     */
    protected $service = 0;
    /**
     * Generated from protobuf field <code>uint64 method = 4;</code>
     */
    protected $method = 0;
    /**
     * Generated from protobuf field <code>repeated .douyin.HeadersList headersList = 5;</code>
     */
    private $headersList;
    /**
     * Generated from protobuf field <code>string payloadEncoding = 6;</code>
     */
    protected $payloadEncoding = '';
    /**
     * Generated from protobuf field <code>string payloadType = 7;</code>
     */
    protected $payloadType = '';
    /**
     * Generated from protobuf field <code>bytes payload = 8;</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $seqId
     *     @type int|string $logId
     *     @type int|string $service
     *     @type int|string $method
     *     @type array<\Douyin\HeadersList>|\Google\Protobuf\Internal\RepeatedField $headersList
     *     @type string $payloadEncoding
     *     @type string $payloadType
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 seqId = 1;</code>
     * @return int|string
     */
    public function getSeqId()
    {
        return $this->seqId;
    }

    /**
     * Generated from protobuf field <code>uint64 seqId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeqId($var)
    {
        GPBUtil::checkUint64($var);
        $this->seqId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 logId = 2;</code>
     * @return int|string
     */
    public function getLogId()
    {
        return $this->logId;
    }

    /**
     * Generated from protobuf field <code>uint64 logId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLogId($var)
    {
        GPBUtil::checkUint64($var);
        $this->logId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 service = 3;</code>
     * @return int|string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>uint64 service = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkUint64($var);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 method = 4;</code>
     * @return int|string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>uint64 method = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkUint64($var);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.HeadersList headersList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeadersList()
    {
        return $this->headersList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.HeadersList headersList = 5;</code>
     * @param array<\Douyin\HeadersList>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeadersList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Douyin\HeadersList::class);
        $this->headersList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payloadEncoding = 6;</code>
     * @return string
     */
    public function getPayloadEncoding()
    {
        return $this->payloadEncoding;
    }

    /**
     * Generated from protobuf field <code>string payloadEncoding = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPayloadEncoding($var)
    {
        GPBUtil::checkString($var, True);
        $this->payloadEncoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string payloadType = 7;</code>
     * @return string
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>string payloadType = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkString($var, True);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 8;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

