<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.RoomUserSeqMessage</code>
 */
class RoomUserSeqMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
     */
    private $ranksList;
    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>string popStr = 4;</code>
     */
    protected $popStr = '';
    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
     */
    private $seatsList;
    /**
     * Generated from protobuf field <code>int64 popularity = 6;</code>
     */
    protected $popularity = 0;
    /**
     * Generated from protobuf field <code>int64 totalUser = 7;</code>
     */
    protected $totalUser = 0;
    /**
     * Generated from protobuf field <code>string totalUserStr = 8;</code>
     */
    protected $totalUserStr = '';
    /**
     * Generated from protobuf field <code>string totalStr = 9;</code>
     */
    protected $totalStr = '';
    /**
     * Generated from protobuf field <code>string onlineUserForAnchor = 10;</code>
     */
    protected $onlineUserForAnchor = '';
    /**
     * Generated from protobuf field <code>string totalPvForAnchor = 11;</code>
     */
    protected $totalPvForAnchor = '';
    /**
     * Generated from protobuf field <code>string upRightStatsStr = 12;</code>
     */
    protected $upRightStatsStr = '';
    /**
     * Generated from protobuf field <code>string upRightStatsStrComplete = 13;</code>
     */
    protected $upRightStatsStrComplete = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type array<\Douyin\RoomUserSeqMessageContributor>|\Google\Protobuf\Internal\RepeatedField $ranksList
     *     @type int|string $total
     *     @type string $popStr
     *     @type array<\Douyin\RoomUserSeqMessageContributor>|\Google\Protobuf\Internal\RepeatedField $seatsList
     *     @type int|string $popularity
     *     @type int|string $totalUser
     *     @type string $totalUserStr
     *     @type string $totalStr
     *     @type string $onlineUserForAnchor
     *     @type string $totalPvForAnchor
     *     @type string $upRightStatsStr
     *     @type string $upRightStatsStrComplete
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRanksList()
    {
        return $this->ranksList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
     * @param array<\Douyin\RoomUserSeqMessageContributor>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRanksList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Douyin\RoomUserSeqMessageContributor::class);
        $this->ranksList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string popStr = 4;</code>
     * @return string
     */
    public function getPopStr()
    {
        return $this->popStr;
    }

    /**
     * Generated from protobuf field <code>string popStr = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPopStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->popStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSeatsList()
    {
        return $this->seatsList;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
     * @param array<\Douyin\RoomUserSeqMessageContributor>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSeatsList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Douyin\RoomUserSeqMessageContributor::class);
        $this->seatsList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 popularity = 6;</code>
     * @return int|string
     */
    public function getPopularity()
    {
        return $this->popularity;
    }

    /**
     * Generated from protobuf field <code>int64 popularity = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPopularity($var)
    {
        GPBUtil::checkInt64($var);
        $this->popularity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 totalUser = 7;</code>
     * @return int|string
     */
    public function getTotalUser()
    {
        return $this->totalUser;
    }

    /**
     * Generated from protobuf field <code>int64 totalUser = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalUser($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalUser = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string totalUserStr = 8;</code>
     * @return string
     */
    public function getTotalUserStr()
    {
        return $this->totalUserStr;
    }

    /**
     * Generated from protobuf field <code>string totalUserStr = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalUserStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->totalUserStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string totalStr = 9;</code>
     * @return string
     */
    public function getTotalStr()
    {
        return $this->totalStr;
    }

    /**
     * Generated from protobuf field <code>string totalStr = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->totalStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string onlineUserForAnchor = 10;</code>
     * @return string
     */
    public function getOnlineUserForAnchor()
    {
        return $this->onlineUserForAnchor;
    }

    /**
     * Generated from protobuf field <code>string onlineUserForAnchor = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOnlineUserForAnchor($var)
    {
        GPBUtil::checkString($var, True);
        $this->onlineUserForAnchor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string totalPvForAnchor = 11;</code>
     * @return string
     */
    public function getTotalPvForAnchor()
    {
        return $this->totalPvForAnchor;
    }

    /**
     * Generated from protobuf field <code>string totalPvForAnchor = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalPvForAnchor($var)
    {
        GPBUtil::checkString($var, True);
        $this->totalPvForAnchor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string upRightStatsStr = 12;</code>
     * @return string
     */
    public function getUpRightStatsStr()
    {
        return $this->upRightStatsStr;
    }

    /**
     * Generated from protobuf field <code>string upRightStatsStr = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUpRightStatsStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->upRightStatsStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string upRightStatsStrComplete = 13;</code>
     * @return string
     */
    public function getUpRightStatsStrComplete()
    {
        return $this->upRightStatsStrComplete;
    }

    /**
     * Generated from protobuf field <code>string upRightStatsStrComplete = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setUpRightStatsStrComplete($var)
    {
        GPBUtil::checkString($var, True);
        $this->upRightStatsStrComplete = $var;

        return $this;
    }

}

