<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.RoomUserSeqMessageContributor</code>
 */
class RoomUserSeqMessageContributor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 score = 1;</code>
     */
    protected $score = 0;
    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>uint64 rank = 3;</code>
     */
    protected $rank = 0;
    /**
     * Generated from protobuf field <code>uint64 delta = 4;</code>
     */
    protected $delta = 0;
    /**
     * Generated from protobuf field <code>bool isHidden = 5;</code>
     */
    protected $isHidden = false;
    /**
     * Generated from protobuf field <code>string scoreDescription = 6;</code>
     */
    protected $scoreDescription = '';
    /**
     * Generated from protobuf field <code>string exactlyScore = 7;</code>
     */
    protected $exactlyScore = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $score
     *     @type \Douyin\User $user
     *     @type int|string $rank
     *     @type int|string $delta
     *     @type bool $isHidden
     *     @type string $scoreDescription
     *     @type string $exactlyScore
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 score = 1;</code>
     * @return int|string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>uint64 score = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkUint64($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @return \Douyin\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.douyin.User user = 2;</code>
     * @param \Douyin\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Douyin\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 rank = 3;</code>
     * @return int|string
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Generated from protobuf field <code>uint64 rank = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRank($var)
    {
        GPBUtil::checkUint64($var);
        $this->rank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 delta = 4;</code>
     * @return int|string
     */
    public function getDelta()
    {
        return $this->delta;
    }

    /**
     * Generated from protobuf field <code>uint64 delta = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelta($var)
    {
        GPBUtil::checkUint64($var);
        $this->delta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isHidden = 5;</code>
     * @return bool
     */
    public function getIsHidden()
    {
        return $this->isHidden;
    }

    /**
     * Generated from protobuf field <code>bool isHidden = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->isHidden = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scoreDescription = 6;</code>
     * @return string
     */
    public function getScoreDescription()
    {
        return $this->scoreDescription;
    }

    /**
     * Generated from protobuf field <code>string scoreDescription = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setScoreDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->scoreDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string exactlyScore = 7;</code>
     * @return string
     */
    public function getExactlyScore()
    {
        return $this->exactlyScore;
    }

    /**
     * Generated from protobuf field <code>string exactlyScore = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setExactlyScore($var)
    {
        GPBUtil::checkString($var, True);
        $this->exactlyScore = $var;

        return $this;
    }

}

