<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.Rsp</code>
 */
class Rsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     */
    protected $a = 0;
    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     */
    protected $b = 0;
    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     */
    protected $c = 0;
    /**
     * Generated from protobuf field <code>string d = 4;</code>
     */
    protected $d = '';
    /**
     * Generated from protobuf field <code>int32 e = 5;</code>
     */
    protected $e = 0;
    /**
     * Generated from protobuf field <code>.douyin.Rsp.F f = 6;</code>
     */
    protected $f = null;
    /**
     * Generated from protobuf field <code>string g = 7;</code>
     */
    protected $g = '';
    /**
     * Generated from protobuf field <code>uint64 h = 10;</code>
     */
    protected $h = 0;
    /**
     * Generated from protobuf field <code>uint64 i = 11;</code>
     */
    protected $i = 0;
    /**
     * Generated from protobuf field <code>uint64 j = 13;</code>
     */
    protected $j = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $a
     *     @type int $b
     *     @type int $c
     *     @type string $d
     *     @type int $e
     *     @type \Douyin\Rsp\F $f
     *     @type string $g
     *     @type int|string $h
     *     @type int|string $i
     *     @type int|string $j
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     * @return int
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * Generated from protobuf field <code>int32 a = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setA($var)
    {
        GPBUtil::checkInt32($var);
        $this->a = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     * @return int
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Generated from protobuf field <code>int32 b = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setB($var)
    {
        GPBUtil::checkInt32($var);
        $this->b = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     * @return int
     */
    public function getC()
    {
        return $this->c;
    }

    /**
     * Generated from protobuf field <code>int32 c = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setC($var)
    {
        GPBUtil::checkInt32($var);
        $this->c = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string d = 4;</code>
     * @return string
     */
    public function getD()
    {
        return $this->d;
    }

    /**
     * Generated from protobuf field <code>string d = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setD($var)
    {
        GPBUtil::checkString($var, True);
        $this->d = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 e = 5;</code>
     * @return int
     */
    public function getE()
    {
        return $this->e;
    }

    /**
     * Generated from protobuf field <code>int32 e = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setE($var)
    {
        GPBUtil::checkInt32($var);
        $this->e = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Rsp.F f = 6;</code>
     * @return \Douyin\Rsp\F|null
     */
    public function getF()
    {
        return $this->f;
    }

    public function hasF()
    {
        return isset($this->f);
    }

    public function clearF()
    {
        unset($this->f);
    }

    /**
     * Generated from protobuf field <code>.douyin.Rsp.F f = 6;</code>
     * @param \Douyin\Rsp\F $var
     * @return $this
     */
    public function setF($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Rsp\F::class);
        $this->f = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string g = 7;</code>
     * @return string
     */
    public function getG()
    {
        return $this->g;
    }

    /**
     * Generated from protobuf field <code>string g = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setG($var)
    {
        GPBUtil::checkString($var, True);
        $this->g = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 h = 10;</code>
     * @return int|string
     */
    public function getH()
    {
        return $this->h;
    }

    /**
     * Generated from protobuf field <code>uint64 h = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setH($var)
    {
        GPBUtil::checkUint64($var);
        $this->h = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 i = 11;</code>
     * @return int|string
     */
    public function getI()
    {
        return $this->i;
    }

    /**
     * Generated from protobuf field <code>uint64 i = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setI($var)
    {
        GPBUtil::checkUint64($var);
        $this->i = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 j = 13;</code>
     * @return int|string
     */
    public function getJ()
    {
        return $this->j;
    }

    /**
     * Generated from protobuf field <code>uint64 j = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setJ($var)
    {
        GPBUtil::checkUint64($var);
        $this->j = $var;

        return $this;
    }

}

