<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

if (false) {
    /**
     * This class is deprecated. Use Douyin\Rsp\F instead.
     * @deprecated
     */
    class Rsp_F {}
}
class_exists(Rsp\F::class);
@trigger_error('Douyin\Rsp_F is deprecated and will be removed in the next major release. Use Douyin\Rsp\F instead', E_USER_DEPRECATED);

