<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.SendMessageBody</code>
 */
class SendMessageBody extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string conversationId = 1;</code>
     */
    protected $conversationId = '';
    /**
     * Generated from protobuf field <code>uint32 conversationType = 2;</code>
     */
    protected $conversationType = 0;
    /**
     * Generated from protobuf field <code>uint64 conversationShortId = 3;</code>
     */
    protected $conversationShortId = 0;
    /**
     * Generated from protobuf field <code>string content = 4;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>repeated .douyin.ExtList ext = 5;</code>
     */
    private $ext;
    /**
     * Generated from protobuf field <code>uint32 messageType = 6;</code>
     */
    protected $messageType = 0;
    /**
     * Generated from protobuf field <code>string ticket = 7;</code>
     */
    protected $ticket = '';
    /**
     * Generated from protobuf field <code>string clientMessageId = 8;</code>
     */
    protected $clientMessageId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conversationId
     *     @type int $conversationType
     *     @type int|string $conversationShortId
     *     @type string $content
     *     @type array<\Douyin\ExtList>|\Google\Protobuf\Internal\RepeatedField $ext
     *     @type int $messageType
     *     @type string $ticket
     *     @type string $clientMessageId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string conversationId = 1;</code>
     * @return string
     */
    public function getConversationId()
    {
        return $this->conversationId;
    }

    /**
     * Generated from protobuf field <code>string conversationId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->conversationId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 conversationType = 2;</code>
     * @return int
     */
    public function getConversationType()
    {
        return $this->conversationType;
    }

    /**
     * Generated from protobuf field <code>uint32 conversationType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setConversationType($var)
    {
        GPBUtil::checkUint32($var);
        $this->conversationType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 conversationShortId = 3;</code>
     * @return int|string
     */
    public function getConversationShortId()
    {
        return $this->conversationShortId;
    }

    /**
     * Generated from protobuf field <code>uint64 conversationShortId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConversationShortId($var)
    {
        GPBUtil::checkUint64($var);
        $this->conversationShortId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 4;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.ExtList ext = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * Generated from protobuf field <code>repeated .douyin.ExtList ext = 5;</code>
     * @param array<\Douyin\ExtList>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExt($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Douyin\ExtList::class);
        $this->ext = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 messageType = 6;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->messageType;
    }

    /**
     * Generated from protobuf field <code>uint32 messageType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkUint32($var);
        $this->messageType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticket = 7;</code>
     * @return string
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Generated from protobuf field <code>string ticket = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTicket($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientMessageId = 8;</code>
     * @return string
     */
    public function getClientMessageId()
    {
        return $this->clientMessageId;
    }

    /**
     * Generated from protobuf field <code>string clientMessageId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientMessageId = $var;

        return $this;
    }

}

