<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.TextFormat</code>
 */
class TextFormat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string color = 1;</code>
     */
    protected $color = '';
    /**
     * Generated from protobuf field <code>bool bold = 2;</code>
     */
    protected $bold = false;
    /**
     * Generated from protobuf field <code>bool italic = 3;</code>
     */
    protected $italic = false;
    /**
     * Generated from protobuf field <code>uint32 weight = 4;</code>
     */
    protected $weight = 0;
    /**
     * Generated from protobuf field <code>uint32 italicAngle = 5;</code>
     */
    protected $italicAngle = 0;
    /**
     * Generated from protobuf field <code>uint32 fontSize = 6;</code>
     */
    protected $fontSize = 0;
    /**
     * Generated from protobuf field <code>bool useHeighLightColor = 7;</code>
     */
    protected $useHeighLightColor = false;
    /**
     * Generated from protobuf field <code>bool useRemoteClor = 8;</code>
     */
    protected $useRemoteClor = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $color
     *     @type bool $bold
     *     @type bool $italic
     *     @type int $weight
     *     @type int $italicAngle
     *     @type int $fontSize
     *     @type bool $useHeighLightColor
     *     @type bool $useRemoteClor
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string color = 1;</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>string color = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bold = 2;</code>
     * @return bool
     */
    public function getBold()
    {
        return $this->bold;
    }

    /**
     * Generated from protobuf field <code>bool bold = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBold($var)
    {
        GPBUtil::checkBool($var);
        $this->bold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool italic = 3;</code>
     * @return bool
     */
    public function getItalic()
    {
        return $this->italic;
    }

    /**
     * Generated from protobuf field <code>bool italic = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setItalic($var)
    {
        GPBUtil::checkBool($var);
        $this->italic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 weight = 4;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>uint32 weight = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 italicAngle = 5;</code>
     * @return int
     */
    public function getItalicAngle()
    {
        return $this->italicAngle;
    }

    /**
     * Generated from protobuf field <code>uint32 italicAngle = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setItalicAngle($var)
    {
        GPBUtil::checkUint32($var);
        $this->italicAngle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 fontSize = 6;</code>
     * @return int
     */
    public function getFontSize()
    {
        return $this->fontSize;
    }

    /**
     * Generated from protobuf field <code>uint32 fontSize = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setFontSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->fontSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool useHeighLightColor = 7;</code>
     * @return bool
     */
    public function getUseHeighLightColor()
    {
        return $this->useHeighLightColor;
    }

    /**
     * Generated from protobuf field <code>bool useHeighLightColor = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseHeighLightColor($var)
    {
        GPBUtil::checkBool($var);
        $this->useHeighLightColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool useRemoteClor = 8;</code>
     * @return bool
     */
    public function getUseRemoteClor()
    {
        return $this->useRemoteClor;
    }

    /**
     * Generated from protobuf field <code>bool useRemoteClor = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseRemoteClor($var)
    {
        GPBUtil::checkBool($var);
        $this->useRemoteClor = $var;

        return $this;
    }

}

