<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.TextEffectDetail</code>
 */
class TextEffectDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Text text = 1;</code>
     */
    protected $text = null;
    /**
     * Generated from protobuf field <code>uint32 textFontSize = 2;</code>
     */
    protected $textFontSize = 0;
    /**
     * Generated from protobuf field <code>.douyin.Image background = 3;</code>
     */
    protected $background = null;
    /**
     * Generated from protobuf field <code>uint32 start = 4;</code>
     */
    protected $start = 0;
    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     */
    protected $duration = 0;
    /**
     * Generated from protobuf field <code>uint32 x = 6;</code>
     */
    protected $x = 0;
    /**
     * Generated from protobuf field <code>uint32 y = 7;</code>
     */
    protected $y = 0;
    /**
     * Generated from protobuf field <code>uint32 width = 8;</code>
     */
    protected $width = 0;
    /**
     * Generated from protobuf field <code>uint32 height = 9;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>uint32 shadowDx = 10;</code>
     */
    protected $shadowDx = 0;
    /**
     * Generated from protobuf field <code>uint32 shadowDy = 11;</code>
     */
    protected $shadowDy = 0;
    /**
     * Generated from protobuf field <code>uint32 shadowRadius = 12;</code>
     */
    protected $shadowRadius = 0;
    /**
     * Generated from protobuf field <code>string shadowColor = 13;</code>
     */
    protected $shadowColor = '';
    /**
     * Generated from protobuf field <code>string strokeColor = 14;</code>
     */
    protected $strokeColor = '';
    /**
     * Generated from protobuf field <code>uint32 strokeWidth = 15;</code>
     */
    protected $strokeWidth = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Text $text
     *     @type int $textFontSize
     *     @type \Douyin\Image $background
     *     @type int $start
     *     @type int $duration
     *     @type int $x
     *     @type int $y
     *     @type int $width
     *     @type int $height
     *     @type int $shadowDx
     *     @type int $shadowDy
     *     @type int $shadowRadius
     *     @type string $shadowColor
     *     @type string $strokeColor
     *     @type int $strokeWidth
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Text text = 1;</code>
     * @return \Douyin\Text|null
     */
    public function getText()
    {
        return $this->text;
    }

    public function hasText()
    {
        return isset($this->text);
    }

    public function clearText()
    {
        unset($this->text);
    }

    /**
     * Generated from protobuf field <code>.douyin.Text text = 1;</code>
     * @param \Douyin\Text $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Text::class);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 textFontSize = 2;</code>
     * @return int
     */
    public function getTextFontSize()
    {
        return $this->textFontSize;
    }

    /**
     * Generated from protobuf field <code>uint32 textFontSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTextFontSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->textFontSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.douyin.Image background = 3;</code>
     * @return \Douyin\Image|null
     */
    public function getBackground()
    {
        return $this->background;
    }

    public function hasBackground()
    {
        return isset($this->background);
    }

    public function clearBackground()
    {
        unset($this->background);
    }

    /**
     * Generated from protobuf field <code>.douyin.Image background = 3;</code>
     * @param \Douyin\Image $var
     * @return $this
     */
    public function setBackground($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Image::class);
        $this->background = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 start = 4;</code>
     * @return int
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>uint32 start = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkUint32($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 x = 6;</code>
     * @return int
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Generated from protobuf field <code>uint32 x = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setX($var)
    {
        GPBUtil::checkUint32($var);
        $this->x = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 y = 7;</code>
     * @return int
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Generated from protobuf field <code>uint32 y = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setY($var)
    {
        GPBUtil::checkUint32($var);
        $this->y = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 width = 8;</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>uint32 width = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkUint32($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 height = 9;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>uint32 height = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowDx = 10;</code>
     * @return int
     */
    public function getShadowDx()
    {
        return $this->shadowDx;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowDx = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setShadowDx($var)
    {
        GPBUtil::checkUint32($var);
        $this->shadowDx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowDy = 11;</code>
     * @return int
     */
    public function getShadowDy()
    {
        return $this->shadowDy;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowDy = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setShadowDy($var)
    {
        GPBUtil::checkUint32($var);
        $this->shadowDy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowRadius = 12;</code>
     * @return int
     */
    public function getShadowRadius()
    {
        return $this->shadowRadius;
    }

    /**
     * Generated from protobuf field <code>uint32 shadowRadius = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setShadowRadius($var)
    {
        GPBUtil::checkUint32($var);
        $this->shadowRadius = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shadowColor = 13;</code>
     * @return string
     */
    public function getShadowColor()
    {
        return $this->shadowColor;
    }

    /**
     * Generated from protobuf field <code>string shadowColor = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setShadowColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->shadowColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string strokeColor = 14;</code>
     * @return string
     */
    public function getStrokeColor()
    {
        return $this->strokeColor;
    }

    /**
     * Generated from protobuf field <code>string strokeColor = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setStrokeColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->strokeColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 strokeWidth = 15;</code>
     * @return int
     */
    public function getStrokeWidth()
    {
        return $this->strokeWidth;
    }

    /**
     * Generated from protobuf field <code>uint32 strokeWidth = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setStrokeWidth($var)
    {
        GPBUtil::checkUint32($var);
        $this->strokeWidth = $var;

        return $this;
    }

}

