<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dy.proto

namespace Douyin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>douyin.UpdateFanTicketMessage</code>
 */
class UpdateFanTicketMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     */
    protected $common = null;
    /**
     * Generated from protobuf field <code>string roomFanTicketCountText = 2;</code>
     */
    protected $roomFanTicketCountText = '';
    /**
     * Generated from protobuf field <code>uint64 roomFanTicketCount = 3;</code>
     */
    protected $roomFanTicketCount = 0;
    /**
     * Generated from protobuf field <code>bool forceUpdate = 4;</code>
     */
    protected $forceUpdate = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Douyin\Common $common
     *     @type string $roomFanTicketCountText
     *     @type int|string $roomFanTicketCount
     *     @type bool $forceUpdate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @return \Douyin\Common|null
     */
    public function getCommon()
    {
        return $this->common;
    }

    public function hasCommon()
    {
        return isset($this->common);
    }

    public function clearCommon()
    {
        unset($this->common);
    }

    /**
     * Generated from protobuf field <code>.douyin.Common common = 1;</code>
     * @param \Douyin\Common $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Douyin\Common::class);
        $this->common = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roomFanTicketCountText = 2;</code>
     * @return string
     */
    public function getRoomFanTicketCountText()
    {
        return $this->roomFanTicketCountText;
    }

    /**
     * Generated from protobuf field <code>string roomFanTicketCountText = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomFanTicketCountText($var)
    {
        GPBUtil::checkString($var, True);
        $this->roomFanTicketCountText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 roomFanTicketCount = 3;</code>
     * @return int|string
     */
    public function getRoomFanTicketCount()
    {
        return $this->roomFanTicketCount;
    }

    /**
     * Generated from protobuf field <code>uint64 roomFanTicketCount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomFanTicketCount($var)
    {
        GPBUtil::checkUint64($var);
        $this->roomFanTicketCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool forceUpdate = 4;</code>
     * @return bool
     */
    public function getForceUpdate()
    {
        return $this->forceUpdate;
    }

    /**
     * Generated from protobuf field <code>bool forceUpdate = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setForceUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->forceUpdate = $var;

        return $this;
    }

}

